#!/bin/bash

HAS_RERUN_A_WORKFLOW=false

ref_names=$(gh pr list --json headRefName,reviewDecision --jq '.[] | select(.reviewDecision == "APPROVED") | .headRefName')
for ref_name in $ref_names; do
  workflow_ids=$(gh run list -b "$ref_name" --json conclusion,databaseId --jq '.[] | select(.conclusion == "failure") | .databaseId')
  for workflow_id in $workflow_ids; do
    gh run rerun "$workflow_id"
    HAS_RERUN_A_WORKFLOW=true
  done

  if [[ $HAS_RERUN_A_WORKFLOW == true ]]; then
    echo "Rerun failed jobs for branch $ref_name"
    exit 0
  fi
done
