name: "Setup Node"
description: "Setup Node"
inputs:
  something:
    description: "Node version"
    required: true
    default: true
runs:
  using: "composite"
  steps:
    - name: Running
      if: inputs.something == 'true'
      shell: bash
      run: echo 'yes'
