name: "Setup Node"
description: "Setup Node"
inputs:
  setup-node:
    description: "Wether to setup node or not"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Should run
      if: inputs.setup-node == 'true'
      run: echo 'running'
    - uses: actions/setup-node@v3
      if: inputs.setup-node == 'true'
