name: "Setup Node"
description: "Setup Node"
runs:
  using: "composite"
  steps:
    - name: Should work
      if: ${{ contains(github.event.pull_request.labels.*.name, 'hellooooooo') }}
      shell: bash
      run: exit 0
    - name: Should not work
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'hellooooooo') }}
      shell: bash
      run: exit 1
