name: Rerun Failed workflows if they are stuck

on:
  schedule:
    - cron: "*/01 * * * *"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rerun_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rerun Failed Jobs
        run: |
          # check if latest commit on main was more than 90 minutes ago
          last_commit=$(gh api repos/ureciocais/testing-workflows/commits/main --jq '.commit.author.date')
          last_commit_timestamp=$(date -d "$last_commit" +%s)
          current_timestamp=$(date +%s)
          diff=$(($current_timestamp - $last_commit_timestamp))
          if [[ $diff -lt 60 ]]; then
            echo "Latest commit on main was less than 1 minute ago. Exiting..."
            exit 0
          fi

          HAS_RERUN_A_WORKFLOW=false
          gh pr list --json headRefName,reviewDecision --jq '.[] | select(.reviewDecision == "APPROVED") | .headRefName' | while read -r ref_name; do
            gh run list -b "$ref_name" --json conclusion,databaseId --jq '.[] | select(.conclusion == "failure") | .databaseId' | while read -r workflow_id; do
              echo "Rerunning workflow $workflow_id for branch $ref_name"
              gh run rerun $workflow_id
              HAS_RERUN_A_WORKFLOW=true
            done

            if [[ $HAS_RERUN_A_WORKFLOW == true ]]; then
              echo "Rerun failed jobs for branch $ref_name"
              exit 0
            fi
          done

          echo "Did not find any PR with failing workflows. Exiting..."
