name: Reusable

on:
  workflow_call:
    inputs:
      anotherthing:
        description: "Another thing"
        required: true
        type: "string"

env:
  SOME_ENV_VAR: ${{ github.event.inputs.SOME_ENV_VAR }}
  OTHER_VAR: ${{ github.event.before }}

jobs:
  something-that-fails:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.SOME_ENV_VAR }}
      - run: echo "$OTHER_VAR"
      - run: echo "$anotherthing"
