name: Reusable

on:
  workflow_call:
    inputs:
      SOME_ENV_VAR:
        description: "Some env var"
        required: true
        type: string

env:
  SOME_ENV_VAR: ${{ inputs.SOME_ENV_VAR }}

jobs:
  something-that-fails:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.SOME_ENV_VAR }}
