name: Reusable

on: workflow_call

env:
  SOME_ENV_VAR: "some value"

jobs:
  something-that-fails:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.some-input }}
      - run: echo ${{ env.SOME_ENV_VAR }}
